{
  "NServiceBus.MessageId": "5c0c9981-8b5e-440e-872b-a82c008f1ae6",
  "NServiceBus.MessageIntent": "Send",
  "NServiceBus.ReplyToAddress": "Sales",
  "NServiceBus.CorrelationId": "5bf7c04b-0e18-4f72-91c4-a82c008f1a76",
  "NServiceBus.OriginatingMachine": "DESKTOP-TQAN4CG",
  "NServiceBus.OriginatingEndpoint": "Sales",
  "$.diagnostics.originating.hostid": "f0537806032cb850d763396e2821a608",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "Messages.Commands.StartOrder, Messages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.RelatedTo": "5bf7c04b-0e18-4f72-91c4-a82c008f1a76",
  "NServiceBus.ConversationId": "8c40ef4f-4d26-4819-bbce-a82c008f1a85",
  "NServiceBus.Version": "6.4.1",
  "NServiceBus.TimeSent": "2017-11-15 08:41:01:786209 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.InvalidOperationException",
  "NServiceBus.Retries.Timestamp": "2017-11-15 08:41:35:081868 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "No handlers could be found for message type: Messages.Commands.StartOrder",
  "NServiceBus.ExceptionInfo.Source": "NServiceBus.Core",
  "NServiceBus.ExceptionInfo.StackTrace": "System.InvalidOperationException: No handlers could be found for message type: Messages.Commands.StartOrder\u000d\u000a   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\LoadHandlersConnector.cs:line 31\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\DeserializeLogicalMessagesConnector.cs:line 33\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ReceivePerformanceDiagnosticsBehavior.cs:line 40\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Performance\\Statistics\\ProcessingStatisticsBehavior.cs:line 27\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\Incoming\\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 37\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Pipeline\\MainPipelineExecutor.cs:line 32\u000d\u000a--- End of stack trace from previous location where exception was thrown ---\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\u000d\u000a   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\u000d\u000a   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext() in C:\\BuildAgent\\work\\a93f853f0c1b9532\\src\\NServiceBus.Core\\Transports\\Learning\\LearningTransportMessagePump.cs:line 277",
  "NServiceBus.TimeOfFailure": "2017-11-15 08:42:31:393567 Z",
  "NServiceBus.FailedQ": "Sales",
  "NServiceBus.ProcessingMachine": "DESKTOP-TQAN4CG",
  "NServiceBus.ProcessingEndpoint": "Sales",
  "$.diagnostics.hostid": "f0537806032cb850d763396e2821a608",
  "$.diagnostics.hostdisplayname": "DESKTOP-TQAN4CG"
}